# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .get_v_10_ssl_live_response_ssl_certificates_item import GetV10SslLiveResponseSslCertificatesItem


class GetV10SslLiveResponse(UniversalBaseModel):
    domain_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="domainName")] = None
    query_time: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="queryTime")] = None
    ssl_certificates: typing_extensions.Annotated[
        typing.Optional[typing.List[GetV10SslLiveResponseSslCertificatesItem]], FieldMetadata(alias="sslCertificates")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
