# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostV20DnsBulkLiveResponseBulkDnsInfoItemDnsRecordsItem(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[int] = None
    dns_type: typing.Optional[str] = None
    ttl: typing.Optional[int] = None
    address: typing.Optional[str] = None
    target: typing.Optional[str] = None
    raw_text: typing.Optional[str] = None
    rrset_type: typing.Optional[int] = None
    single_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
