# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PostV20DnsBulkLiveResponseBulkDnsInfoItemDnsTypes(UniversalBaseModel):
    ptr: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="PTR")] = None
    a: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="A")] = None
    mx: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="MX")] = None
    ns: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="NS")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
