# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v_10_bulkwhois_response_bulk_whois_response_item import PostV10BulkwhoisResponseBulkWhoisResponseItem


class PostV10BulkwhoisResponse(UniversalBaseModel):
    bulk_whois_response: typing.Optional[typing.List[PostV10BulkwhoisResponseBulkWhoisResponseItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
