# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v_20_dns_bulk_live_response_bulk_dns_info_item import PostV20DnsBulkLiveResponseBulkDnsInfoItem


class PostV20DnsBulkLiveResponse(UniversalBaseModel):
    bulk_dns_info: typing.Optional[typing.List[PostV20DnsBulkLiveResponseBulkDnsInfoItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
