# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PostV10BulkwhoisResponseBulkWhoisResponseItemDomainRegistrar(UniversalBaseModel):
    iana_id: typing.Optional[str] = None
    registrar_name: typing.Optional[str] = None
    whois_server: typing.Optional[str] = None
    website_url: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone_number: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
